# Generated by Django 3.1.3 on 2020-12-15 17:22

from django.db import migrations, models
import user.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201207_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[user.validators.CustomPhoneNumberValidator()], verbose_name='Номер Телефону'),
        ),
    ]
