# Generated by Django 3.1.3 on 2021-01-13 15:53


import uuid

from django.db import migrations, models


def fill_custom_user_uuid(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    CustomUser = apps.get_model('user', 'CustomUser')
    for obj in CustomUser.objects.using(db_alias).all():
        obj.uuid = uuid.uuid4()
        obj.save()


class Migration(migrations.Migration):
    """ Change model with integer pk to UUID pk.  This migration presumes there
    are no db constraints (foreign keys) to this table.
    """

    dependencies = [
        ('user', '0004_auto_20210113_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='uuid',
            field=models.UUIDField(null=True),
        ),
        migrations.RunPython(fill_custom_user_uuid, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='customuser',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, serialize=False, editable=False, unique=True),
        ),
        migrations.RemoveField('CustomUser', 'id'),
        migrations.RenameField(
            model_name='customuser',
            old_name='uuid',
            new_name='id'
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(primary_key=True, default=uuid.uuid4, serialize=False, editable=False),
        ),
    ]
