version: '3.7'
volumes:
  pgdata:
services:
  postgres:
    image: postgres:12
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
    - "5432:5432"
  django:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/web
    ports:
      - "8000:8000"
    depends_on:
      - postgres
