# Generated by Django 3.1.3 on 2020-11-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debts',
            name='modified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Модифіовано'),
        ),
        migrations.AlterField(
            model_name='income',
            name='modified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Модифіовано'),
        ),
    ]
