# Generated by Django 3.1.3 on 2020-12-04 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20201128_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name="Ім'я")),
                ('description', models.TextField(max_length=500, verbose_name='Опис')),
            ],
        ),
        migrations.AlterModelOptions(
            name='debts',
            options={'verbose_name': 'Борг', 'verbose_name_plural': 'Борги'},
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'verbose_name': 'Прибуток', 'verbose_name_plural': 'Прибутки'},
        ),
        migrations.AddField(
            model_name='debts',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='debt', to='user.customuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='income', to='user.customuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='debts',
            name='debt_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Час зміни'),
        ),
        migrations.AlterField(
            model_name='debts',
            name='debtor_name',
            field=models.CharField(max_length=100, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='debts',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='debts',
            name='mod',
            field=models.CharField(choices=[('+', 'Позичати (у когось)'), ('-', 'Позичити (комусь)')], max_length=1, verbose_name='Модифікатор'),
        ),
        migrations.AlterField(
            model_name='debts',
            name='prise',
            field=models.PositiveIntegerField(verbose_name='Значення'),
        ),
        migrations.AlterField(
            model_name='income',
            name='description',
            field=models.PositiveIntegerField(verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='income',
            name='prise',
            field=models.PositiveIntegerField(verbose_name='Прибуток'),
        ),
        migrations.AddField(
            model_name='income',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income', to='core.category'),
        ),
    ]
