# Generated by Django 3.1.3 on 2020-12-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201207_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debts',
            name='description',
            field=models.CharField(db_index=True, max_length=500, verbose_name='Опис'),
        ),
    ]
