# Generated by Django 3.1.3 on 2020-12-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201207_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debts',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Опис'),
        ),
    ]
