# Generated by Django 3.1.3 on 2021-01-13 15:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_cost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Debts',
            new_name='Debt',
        ),
    ]
