# Generated by Django 3.1.3 on 2021-02-08 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210202_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='debtor_name',
            field=models.CharField(max_length=100, verbose_name="Ім'я"),
        ),
        migrations.AddConstraint(
            model_name='debt',
            constraint=models.UniqueConstraint(fields=('user', 'debtor_name'), name='debtor constraint'),
        ),
    ]
