# Generated by Django 3.1.3 on 2021-03-02 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('core', '0011_auto_20210225_1042'), ('core', '0012_auto_20210228_1601'), ('core', '0013_auto_20210228_2322'), ('core', '0014_auto_20210228_2327'), ('core', '0015_remove_transaction_user'), ('core', '0016_transaction_date'), ('core', '0017_auto_20210302_1228')]

    dependencies = [
        ('core', '0010_auto_20210208_0005'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Створено')),
                ('modified_at', models.DateTimeField(blank=True, null=True, verbose_name='Модифіовано')),
                ('prise', models.PositiveIntegerField(verbose_name='Сума')),
                ('description', models.PositiveIntegerField(verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Транзакція',
                'verbose_name_plural': 'Транзакції',
            },
        ),
        migrations.RemoveField(
            model_name='income',
            name='category',
        ),
        migrations.RemoveField(
            model_name='income',
            name='user',
        ),
        migrations.RemoveField(
            model_name='debt',
            name='mod',
        ),
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('+', 'Дохід'), ('-', 'Витрата')], default='-', max_length=1, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='debt',
            name='mode',
            field=models.CharField(choices=[('+', 'Позичити (у когось)'), ('-', 'Позичити (комусь)')], default='-', max_length=1, verbose_name='Модифікатор'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=40, unique=True, verbose_name="Ім'я"),
        ),
        migrations.DeleteModel(
            name='Cost',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction', to='core.category'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=40, verbose_name="Ім'я"),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='category constraint'),
        ),
        migrations.AlterField(
            model_name='category',
            name='user',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='user.customuser'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.AddField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Час виконання'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Опис'),
        ),
    ]
