# Generated by Django 3.1.3 on 2021-03-02 21:55

from django.db import migrations


def transaction_category(apps, schema_editor):
    Transaction = apps.get_model('core', 'Transaction')
    Category = apps.get_model('core', 'Category')
    obj = Category.objects.get(id=33)
    for transaction in Transaction.objects.all():
        if not transaction.category:
            transaction.category = obj
            transaction.save()


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0011_auto_20210225_1042_squashed_0017_auto_20210302_1228'),
    ]

    operations = [migrations.RunPython(transaction_category)
                  ]
